server:
  port: 7001

eureka:
  client:
    register-with-eureka: true

#spring:
#  application:
#    name: Booking-Service
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          lob:
#            non_contextual_creation: true
#    hibernate:
#      ddl-auto: update
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://postgresqldb:5432/bus_booking
#    username: postgres
#    password: mysecretpassword
#  sql:
#    init:
#      mode: always
#      platform: postgres

spring:
  application:
    name: Booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bus_booking
    username: postgres
    password: atumar4031
  jpa:
    hibernate:
      ddl-auto: update