server:
  port: 7002
eureka:
  client:
    register-with-eureka: true
spring:
  application:
    name: Payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_service
    username: postgres
    password: atumar4031
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true